config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  resources :cocktails, only: [:index, :show, :new, :create, :destroy] do
    resources :doses, only: [:new, :create]
  end

  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true, allow_blank: false
  validates_uniqueness_of :cocktail_id, :scope => [:ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail
    else
      render 'new'
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path, notice: "You just destroyed a cocktail. Why would you do that?"
  end

 private
  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :description)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    # need s a dose and a cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    # puts a value of cockfail's ID in doses' foreign key
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for([@cocktail]) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit id: "cocktail-submit" %>
<% end %>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path("cocktails/alcohol-bar-beer-1283219.jpg", :effect=>"blur:355", :gravity=>"xy_center", :height=>642, :width=>1327, :crop=>"fill") %>); height: calc(100vh - 50px);">

      <div class="banner-content">
        <h1 id="home-header">Mix World</h1>
       <a href="#cocktail-cards"><btn class="home-banner-button">Browse drinks </btn></a> | <btn class="home-banner-button"> <%= link_to "add your own", new_cocktail_path %></btn>

      </div>
  </div>
<div class="container" id="home-container">
    <div class="container cocktail-cards-container" id="cocktail-cards">
        <div class="row" style="justify-content: center">
            <% @cocktails.each do |c| %>
              <div class="cocktail-card col-xs-12 col-sm-6 lg-4 magnify"
              style=" background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
              url('<%= cl_image_path c.photo, height: 300, width: 400, crop: :fill unless c.photo.blank? %>')">
              <div class="card-drink"> <h2 class="drink-name"><%= link_to c.name, cocktail_path(c), class: "cocktail-card-title" %></h2>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <img src="images/logo.png" alt="logo">
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <a href="" class="navbar-wagon-item navbar-wagon-link">Host</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Trips</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Messages</a>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container" id="cocktail-new-container">
<h1 style="font-size: 30px">New cocktail</h1>
  <div class="form-container">
<%= render 'form', cocktail: @cocktail %>
  </div>
</div>

app/views/cocktails/show.html.erb
<% photo = @cocktail.photo.url ? cl_image_path(@cocktail.photo, transformation: {height: 400}) : 'https://www.pexels.com/photo/close-up-photo-of-clear-drinking-glass-with-black-liquid-1282272' %>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= photo %>);">
  <div class="banner-content">
    <h1> <%= @cocktail.name %> </h1>
  </div>
</div>

<div class="container-show">
  <div class="cocktail-show">
    <div class="cocktail-description">
      <div id="description-title-colorblock">
      <h2 class="cocktail-show-header">Description:</h2>
      </div>
      <p><%= @cocktail.description %></p>
      <div id="nav-icons">
     <%= link_to '<i class="fas fa-step-backward"></i>'.html_safe, cocktails_path %> |
     <%= link_to '<i class="fa fa-trash"></i>'.html_safe, cocktail_path(@cocktail), method: :delete %>
      </div>
    <!--   <%= cl_image_tag @cocktail.photo, {:style => "height: 300px; width: 300px"} %> -->
    </div>
    <div class="cocktail-title-ingredients">
    <div class="cocktail-ingredients">
      <h2 class="cocktail-show-header">Ingredients:</h2>
    <% @cocktail.doses.each do |dose| %>
      <li>
        <%= dose.ingredient.name %> - <%= dose.description %>
        <%= link_to '<i class="fa fa-trash"></i>'.html_safe, dose_path(dose), method: :delete, id: "dose-delete-button" %>
      </li>
      <% end %>
      <br>
      <p id="ingredient-tip">Not how you like it? Add an ingredient below!</p>
      <%= render 'doses/form', cocktail: @cocktail, dose: @dose %>
    </div>
    </div>
  </div>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.association :ingredient, id: "add-ingredient" %>
  <%= f.input :description, label: "Amount", id: "add-amount" %>
  <%= f.submit "Add", id: "cocktail-submit" %>
<% end  %>

app/views/doses/new.html.erb
<%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.input :description, label: "Amount" %>
  <%= f.association :ingredient %>
  <%= f.submit %>
<% end  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <div class="container-fluid">
    <!-- Nav Header -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse-1" aria-expanded="false">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand", id: "cocktail_logo_navbar" do %>
        <%= image_tag "cocktail_logo_white.png", height: 30; %>
        <% end %>
     <!--  <a class="navbar-brand" href="#"><span class="fa fa-home"></span><span class="link"> Home</span></a> -->
    </div>
    <!-- Nav Collapse -->
    <div class="navbar-collapse collapse" id="collapse-1">
      <!-- Nav Left -->
      <ul class="nav navbar-nav">
        <li><%= link_to "Add a cocktail!", new_cocktail_path %></li>
      </ul>
      <!-- Nav Right -->
      <form class="navbar-form navbar-right">
        <div class="form-group">
       <!--    <input type="text" class="form-control" placeholder="Search"> -->
        </div>
        <button type="submit" class="btn"><span class="fa fa-search"></span></button>
      </form>
    </div>
  </div>
</nav>